config/routes.rb
Rails.application.routes.draw do
  get 'answers/edit'
  
  root 'questions#index'
  resources :questions do
    resources :answers
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    #questionに紐づく
  belongs_to :question
  
    #バリデーション設定-空文字×
  validates :name, presence: true
  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  #複数のanswerがあるけど、親が削除されたら全て削除される
  has_many :answers, dependent: :destroy
  
  
  #バリデーション設定-空文字×
  validates :name, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: [ :edit, :update, :destroy]
  
  def create
    
     @answer = Answer.new
     if @answer.update(answer_params)
       redirect_to question_path(@question), notice: 'Success!'
     else
       redirect_to question_path(@question), alert: 'Invalid!'
     end
  end
  
  def edit
    @answer = @question.answers.find(params[:id])
  end
  
  def update
    @answer = @question.answers.find(params[:id])
    if @answer.update(answer_params)
       redirect_to question_path(@question), notice: 'Success!'
    else
       redirect_to question_path(@question), alert: 'Invalid!'
    end
  end
  
   #削除
  def destroy
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question), notice: 'DeletedDeleted!'
  end
  
  private
    def set_question
      @question = Question.find(params[:question_id])
    end
    def answer_params
      params.require(:answer).permit(:content, :name, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [ :show, :edit, :update, :destroy]
   
  def index
    @questions = Question.all
  end
  
  #詳細確認
  def show
    @answer = Answer.new
  end
  
  #新規作成
  def new
    @question = Question.new
  end
  
  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path, notice: 'Success!'
    else
      flash[:alert] = 'Save error!'
      render :new
    end
  end
  
  def edit

  end
  #更新
  def update
    if @question.update(question_params)
      redirect_to root_path, notice: 'Success!'
    else
      flash[:alert] = 'Save error!'
      render :edit
    end
  end
  
  #削除
  def destroy
    @question.destroy
    redirect_to root_path, notice: 'Success!'
  end
  
  
  private
    #共通化処理
    def set_question
      @question = Question.find(params[:id])
    end
    #送られてきた内容を正確に絞る ストロングパラメーター
    def question_params
      params.require(:question).permit(:name, :title, :content)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/edit.html.erb
<div>
    <h2>Update answer</h2>
    <%= form_with model: [@question, @answer], local: true do |f| %>
      <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Content</label>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="text-center">
        <%= f.submit "Update", class: 'btn btn-primary' %>
      </div>
      
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qanda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Q and Aアプリ</h1>
    </header>
  <!--表示する文字についてはコントローラーで設定済み-->
    <% if flash[:notice] %>
      <p class="text-success"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="text-danger"><%= flash[:alert] %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: @question, local: true do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Content</label>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="text-center">
    <%= f.submit "保存", class: "btn btn-primary" %>
    <%= link_to :back do %>
      <button class="btn btn-secondary">戻る</button>
    <% end %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center">Edit Question</h2>
    <!--アンスコ取ったもの-->
    <%= render 'form' %>
  </div>
</div>

app/views/questions/index.html.erb
<h2 class="title">質問一覧</h2>
<div class="row">
  <div class="col-md-12 col-sm-12">
    <table class="table table-striped">
      <thead class="thead-light">
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Menu</th>
        </tr>
      </thead>
      <tbody>
         <% @questions.each do |question| %>
          <tr>
             <td><%= question.id %></td>
             <!--詳細確認showメソッドへ-->
             <td><%= link_to question.title, question_path(question) %></td>
             <td>
               <!--引数はurlの中に埋め込まれる　IDとしても使用可能 -->
              <%= link_to 'Edit', edit_question_path(question) %>
              <%= link_to 'Delete', question_path(question), method: :delete, data: {confirm: 'Are you sure?' } %>
               </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center">
      <%= link_to new_question_path do %>
        <button class="btn btn-primary">新しく質問をする</button>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center">質問をする</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2><%= @question.title %></h2>
    <div>
      Content: <%= @question.content %>
    </div>
    <div>
      Name: <%= @question.name %>
    </div>
    <hr>
    
    <div class="section">
      <h3 class="title">回答一覧</h3>
      <table class="table table-striped">
         <!--1件以上ある場合表示--->
        <% if @question.answers.any? %>
          <thead class="thead-light">
            <tr>
              <td>Answer</td>
              <td>Name</td>
              <td>Menu</td>
            </tr>
          </thead>
          <tbody>
            <% @question.answers.each do |answer| %>
              <tr>
                <td>
                  <%= answer.content %>
                </td>
                <td>
                  <%= answer.name %>
                </td>
                <td>
                  [<%= link_to 'Edit', edit_question_answer_path(@question, answer) %>]
                  [<%= link_to 'Delete', question_answer_path(@question, answer), 
                    method: :delete, data:{ confirm: 'Are you sure?'} %> ]
                </td>
              </tr>
            <% end %>
          </tbody>
        <% else %>
          <p>No answer yet.</p>
        <% end %>
        
      </table>
     
    </div>
    <div class="section">
         <h3 class="title">新しい回答を投稿する</h3>
        <!--answerコントローラーへ送信する-->
        <%= form_with model: [@question, @answer], local: true do |f| %>
        <!--hiddenパラメーター @question.idも合わせて送信するため--->
          <%= f.hidden_field :question_id, { value: @question.id} %>
          <div class="form-group">
            <label>Name</label>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label>Content</label>
            <%= f.text_area :content, class: 'form-control' %>
          </div>
          <div class="text-center">
            <%= f.submit "投稿", class: 'btn btn-primary' %>
            <%= link_to :back do %>
              <button class="btn btn-secondary">戻る</button>
            <% end %>
          </div>
        <% end %>
    </div>
    <div>
      <%= link_to '> ホームへ戻る', root_path %>
    </div>
  </div>
</div>